"""Initial migration: events, participants, candidates, votes

Revision ID: 7a918ba42940
Revises: 
Create Date: 2025-10-14 22:13:01.947487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a918ba42940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('allow_vote', sa.Boolean(), nullable=True),
    sa.Column('final_decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_deleted_at', 'events', ['deleted_at'], unique=False)
    op.create_index('ix_events_expires_at', 'events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Integer(), nullable=True),
    sa.Column('distance_from_center', sa.Float(), nullable=True),
    sa.Column('in_circle', sa.Boolean(), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidates_event_id', 'candidates', ['event_id'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index('ix_candidates_place_id', 'candidates', ['place_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('fuzzy_lat', sa.Float(), nullable=True),
    sa.Column('fuzzy_lng', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_participants_event_id', 'participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_votes_event_id', 'votes', ['event_id'], unique=False)
    op.create_index('ix_votes_participant_candidate', 'votes', ['participant_id', 'candidate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_participant_candidate', table_name='votes')
    op.drop_index('ix_votes_event_id', table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index('ix_participants_event_id', table_name='participants')
    op.drop_table('participants')
    op.drop_index('ix_candidates_place_id', table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index('ix_candidates_event_id', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('ix_events_expires_at', table_name='events')
    op.drop_index('ix_events_deleted_at', table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
