"""Add custom center to events

Revision ID: cb2b543a7fe9
Revises: 6fad2bf80012
Create Date: 2025-10-16 23:33:35.257401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2b543a7fe9'
down_revision = '6fad2bf80012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('custom_center_lat', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('custom_center_lng', sa.Float(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('events', 'custom_center_lng')
    op.drop_column('events', 'custom_center_lat')
    # ### end Alembic commands ###
